services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: license-plate-detection
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    command: ["python3", "main.py", "--help"]